#ifndef LAPACK_DEFINES_H
#define LAPACK_DEFINES_H

// auto-generated by: configure.py static=1 prefix=buildd
//  
// host: fedora
//
// Definitions for:
// CXX   = g++
//         
// LIBS  = -llapacke -ltmglib -llapack -lcblas -lblas
//         
//         

#define LAPACK_FORTRAN_ADD_
#define LAPACK_HAVE_CBLAS
#define LAPACK_HAVE_LAPACK
#define LAPACK_VERSION 31100
#define LAPACK_HAVE_MATGEN
#define LAPACK_HAVE_LAPACKE


#endif /* LAPACK_DEFINES_H */
